//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.04 at 03:16:23 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://pojo.soap.com/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soap.pojo;
